In [1]:
import tensorflow as tf

/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.reset_default_graph()

actual_return = tf.Variable([[0.0, 0.0, 0.0]], name='actual_return', dtype=tf.float32, validate_shape=False)


In [3]:
saver = tf.train.Saver()

In [6]:
with tf.Session() as sess:
    # Restore variables from disk.
    saver.restore(sess, "./qlV.ckpt-200")
    print("Model restored.")
    # Check the values of the variables
    print("AR : %s" % actual_return.eval())


INFO:tensorflow:Restoring parameters from ./qlV.ckpt-200
Model restored.
AR : [[ 0.0000000e+00  5.6463897e-02 -2.7765508e-03]
 [ 6.3789451e-01  0.0000000e+00  5.5113557e-04]
 [ 7.3489988e-01  3.7517268e-05  5.5378873e-04]
 [ 0.0000000e+00  5.4136995e-02  5.5027689e-04]
 [ 0.0000000e+00  5.8910441e-02  5.6509790e-04]
 [ 0.0000000e+00  3.9299826e-05  9.2748123e-01]
 [ 0.0000000e+00  6.1947662e-02  5.4724555e-04]
 [ 4.9026014e-04  5.6238383e-02  5.4724555e-04]
 [ 7.5641739e-01  0.0000000e+00  5.6064816e-04]
 [ 0.0000000e+00  3.7667713e-05  9.2189980e-01]]
